name: Build Lazarus Win64

on:
  release:
    types: [created]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Lazarus
      uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: stable

    - name: Build project
      run: |
        cd src
        lazbuild calc2plus3.lpi

    - name: Upload exe to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/calc2plus3.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
