name: Build and Release Win64

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Setup Lazarus
      uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: stable

    - name: Build project
      run: lazbuild --build-mode=Release src/calc2plus3.lpi

    - name: Upload exe to GitHub Release
      uses: softprops/action-gh-release@v3
      with:
        files: build/calc2plus3.exe
        token: ${{ secrets.GITHUB_TOKEN }}

